version: "3.7"

services:
  web:
    image: ghcr.io/volrabp/satoshi-zap:1.2.36
    restart: on-failure
    environment:
      - PORT=3020
      - LNBITS_URL=http://172.17.0.1:3007
      - LNBITS_BASE_URL=http://172.17.0.1:3007
      - HTTPS_ENABLED=false
      - UMBREL=true
      - LICENSE_SERVER_URL=https://satoshi-zap-license-worker.volrabp.workers.dev
      - MOCK_LICENSE=false
    ports:
      - "3020:3020"
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
