version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: web
      APP_PORT: 3020
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/volrabp/satoshi-zap:1.2.50
    restart: on-failure
    mem_limit: 512m
    environment:
      - PORT=3020
      - LNBITS_URL=http://172.17.0.1:3007
      - LNBITS_BASE_URL=http://172.17.0.1:3007
      - HTTPS_ENABLED=false
      - UMBREL=true
      - LICENSE_SERVER_URL=https://satoshi-zap-license-worker.cybob.workers.dev
      - MOCK_LICENSE=false
    expose:
      - "3020"
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
